name: Build Pyinstaller Executables

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: True
  

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r agent/requirements.txt
          pip install pyinstaller
      # pip install nuitka
      # - name: Create runtime_config.py
      #   shell: pwsh
      #   run: |
      #       @'
      #       SERVER_IP = "1.2.3.4"
      #       AGENT_NAME = "Jay_hanuman"
      #       '@ | Set-Content agent/runtime_config.py
      - name: Build with pyinstaller
        shell: cmd
        run: |
            pyinstaller --onefile --name sentinel-agent agent/main.py
      # python -m nuitka --standalone --onefile  --assume-yes-for-downloads --output-filename=sentinel-agent --output-dir=dist agent/main.py
      # pyinstaller --onefile --name sentinel agent/main.py
            
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/*.exe

  build-linux:
    runs-on: ubuntu-latest
    container: 
      image: python:3.11-bullseye

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r agent/requirements.txt
          pip install pyinstaller
          # pip install nuitka
      
      # - name: Install patchelf (detect package manager)
      #   run: |
      #     if command -v apt-get &> /dev/null; then
      #       echo "Using apt (Debian/Ubuntu)"
      #        apt-get update
      #        apt-get install -y patchelf
      #     elif command -v dnf &> /dev/null; then
      #       echo "Using dnf (Fedora/RHEL)"
      #       dnf install -y patchelf
      #     elif command -v yum &> /dev/null; then
      #       echo "Using yum (older RHEL/CentOS)"
      #       yum install -y patchelf
      #     else
      #       echo "ERROR: No supported package manager found"
      #       exit 1
      #     fi

      - name: Build with pyinstaller
        run: |
          # python -m nuitka --standalone --onefile  --assume-yes-for-downloads --output-filename=sentinel-agent --output-dir=dist agent/main.py
          pyinstaller \
            --onefile \
            --name sentinel-agent \
            agent/main.py
      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: ${{ github.ref_name }}
      #     release_name: Release ${{ github.ref_name }}
      #     files: dist/sentinel-agent.exe
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4